### ISSUE TITLE
Keeping track of the dead

### ISSUE THREAD

**Issue by santaci** [MesserLab/SLiM-Extras#1]
Hello there,
I'm about to have a go with SLiM and have been reading through the manual. I can se that you can keep track of individuals that have died - particularly under a birth-death model but I was wondering if the genotype outputs of those that don't survive in a simulation can also be retained?
Apologies if the questions seems obvious...
Kind regards,
Cindy

**Comment by bhaller** [comment]
Hi.  Please re-ask this on the slim-discuss mailing list.  Closing this issue since it is not an issue.  :->
