### ISSUE TITLE
update ubuntu ppa for new Ubuntu LTS 22.04 jammy

### ISSUE THREAD

**Issue by eoli3n** [MesserLab/SLiM-Extras#22]
http://ppa.launchpad.net/bryce-a-carson/slim-sim/ubuntu/dists/

There is no release for "jammy". Could you update this please ?

**Comment by bhaller** [comment]
@bryce-carson I guess this is one for you?

**Comment by bryce-carson** [comment]
@eoli3n I think Jammy was devel. Does the devel package work?

**Comment by eoli3n** [comment]
```
Run-time Qt version 5.15.3 does not match compile-time Qt version 5.15.2
```

**Comment by eoli3n** [comment]
Anything new ?

**Comment by bryce-carson** [comment]
@eoli3n,

The native DEB packaging method is being abandoned. Debian and Ubuntu users will be serviced with a Flatpak. The complexity of Debian packaging makes maintaining the native DEB binary package format for both Debian and Ubuntu too time–consuming.

If you'd like to maintain a Debian package for Ubuntu users, preferably also for Debian users, then you're welcome to ask any questions about the packaging process that I may be able to shed light on.

For now, the best option is Flatpak (to ensure users do not encounter a Qt build–vs–runtime version mismatch, and to ensure packages are released soon after updates to SLiMgui). The Flatpak repository will soon be generally available.

For deployment to many machines, there are several approaches. I don't know what will work for your situation, but a simple approach would be to use GNU parallel, enabling the Flatpak repository then installing the Flatpak.

**Comment by eoli3n** [comment]
Flatpak is ok to me, let's search where you documented it.

**Comment by bryce-carson** [comment]
@eoli3n 

> The Flatpak repository will soon be generally available.

**Comment by bryce-carson** [comment]
@bhaller, sorry this issue is still open until I actually release the Flatpak.

I'll email you about that soon.
